services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --d winfinity -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - winfinitydb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  winfinitydb:
